[tools]
java = "openjdk-17"
maven = "3.9.4"

# タスクの使用方法:
# mise run <task_name>
# 例:
# - Spring Boot アプリケーションを起動する: mise run sp-run

[tasks.sp-run]
description = 'Spring Bootアプリケーションを起動する'
run = 'mvn spring-boot:run'

[tasks.format-validate]
description = 'main および test ディレクトリにある Java ファイルのフォーマットを検証する'
run = 'mvn formatter:validate'

[tasks.format]
description = 'main および test ディレクトリにある Java ファイルをフォーマットする'
run = 'mvn formatter:format'
